### ISSUE TITLE
User directory different path?

### ISSUE THREAD

**Issue by saas786** [GaryJones/sublime#1]
Hi @GaryJones 

I am interested in using your sublime settings but I am confused.

In your **Install** instructions you are point to path

```
Support/Sublime\ Text 3/Packages/User
```

where as I don't have such path, instead I do have,

```
Support/Sublime\ Text 3/Data/Packages/User
```

I am using the Portable x64 bit version of Sublime text 3.

You input will be appreciated.
Thanks.

**Comment by GaryJones** [comment]
Mine is definitely without the Data directory level on Mac, but I'm also not using it in portable mode either.

![screenshot 2015-01-26 08 05 00](https://cloud.githubusercontent.com/assets/88371/5896717/101090fa-a532-11e4-8ad6-652485738523.png)

So long as your User directory is the one inside the Packages directory, then you should be good to go.

**Comment by saas786** [comment]
Thanks,

I manually installed preferences, theme, etc.

Thanks for sharing it here.
