### ISSUE TITLE
Indentation...

### ISSUE THREAD

**Issue by saas786** [GaryJones/sublime#2]
I used to use NetBeans, but stopped using it, it was wasting too much time because of memory usage by Netbeans, long story short, I started using Sublime about 6 months ago or so.

I am satisfied with it in terms of performance, but its not an ideal IDE like Netbeans is.

One of the main issue, I face is indentation, I just do single click on netbeans it took care of my indentation issues etc. Not in Sublime.

Also, recently I have started following WordPres Coding Standards (PHP, CS), and looking for JS coding style as well.

So,
finally, my question is, how you tackle with it in sublime?

I have inconsistent indentations in different files,

I am sorry I am having hard time explaining :).

What indentation you use for:
PHP
HTML
CSS
JS

Tabs? or Spaces? how many 4, 2?

For CSS / LESS / SCSS I am using Sublime CSSComb package with WPCSS properties.

But while coding, how I can configure sublime, so it automatically let me apply standard indentation for each of these file types.

**Comment by saas786** [comment]
or better if you use .editorconfig?

Do you?

**Comment by GaryJones** [comment]
For WP coding standards, use tab at size 4. Within Sublime, you can change the indentation via the status bar option in the bottom right. Click on it, and you can select tab size 4. Ensure Indent with space is NOT selected.

![screenshot 2015-01-27 14 10 44](https://cloud.githubusercontent.com/assets/88371/5919712/57a4a10c-a62e-11e4-8297-f967de5476aa.png)

You can also reselect it and choose to convert indents from space to tabs. Cmd+Shift+P then type indent also gives you an option to reindent lines.

**Comment by saas786** [comment]
Thanks @GaryJones 

I was confused as I have read lots of coding style guides over the course of last few months, and everyone suggested different indentation techniques for different files.

Will use this.
